'use client';
import Link from 'next/link';
import { ArrowRight, ArrowUpRight, MessageCircle, Pencil, Settings, FileText, Phone } from 'lucide-react';
import { services, processSteps, company, previewMode } from '@/lib/content';
import { MockupPhoto } from '@/components/mockup-photo';
const serviceDescriptions: Record<string,string>={branding:'브랜드 전략 · 로고 · 패키지',video:'홍보 · 제품 · 인터뷰 영상',website:'기업 · 기관 홈페이지',catalog:'기업 · 제품 소개 자료',editorial:'기록과 성과를 담는 편집 디자인'};
const icons=[MessageCircle,Pencil,Settings,FileText];
export default function HomeV4(){return <div className="home-v4">
 <section className="v4-hero">
  <MockupPhoto kind="hero" alt="웹사이트 화면과 영상 편집 모니터, 브랜드 패키지, 카탈로그와 책자가 놓인 작업 공간 디자인 예시" className="v4-hero-photo"/>
  <div className="wrap v4-hero-inner"><div className="v4-hero-copy"><h1>브랜드의 시작부터,<br/>고객을 만나는 모든 순간까지.</h1><p className="v4-services-line">브랜딩 · 동영상 · 홈페이지 · 카탈로그 · 책자 제작</p><p className="v4-hero-description">공공기관과 기업의 목적에 맞춰,<br/>기획부터 디자인과 제작까지 함께합니다.</p><div className="v4-actions"><Link href="/contact" className="button">제작 견적 문의<ArrowRight size={19}/></Link><Link href="/works" className="v4-quiet-link">제작 사례 보기<ArrowUpRight size={16}/></Link></div><p className="v4-motto">좋은 디자인이<br/>더 나은 내일을 만듭니다.</p></div></div><span className="v4-image-note">콘셉트 이미지 · 실제 실적 아님</span>
 </section>
 <section className="v4-services wrap" aria-labelledby="services-title"><div className="v4-section-heading"><h2 id="services-title">디자인미창의 주요 서비스</h2><Link href="/services">서비스 전체 보기<ArrowUpRight size={15}/></Link></div><div className="v4-service-grid">{services.map(s=><Link href={'/services/'+s.id} className="v4-service-card" key={s.id}><div className="v4-service-photo"><MockupPhoto kind={s.id} alt={s.name+' 디자인 예시'}/><span>디자인 예시</span></div><h3>{s.name==='기업·제품 카탈로그'?'카탈로그':s.name}</h3><p>{serviceDescriptions[s.id]}</p></Link>)}</div></section>
 <section className="v4-process"><div className="wrap v4-process-inner"><div className="v4-process-intro"><h2>필요한 작업을,<br/>하나의 흐름으로.</h2><p>처음부터 끝까지, 같은 생각으로<br/>더 좋은 결과를 만듭니다.</p></div><ol>{processSteps.map((s,i)=>{const Icon=icons[i];return <li key={s.title}><Icon size={32} strokeWidth={1.15} aria-hidden="true"/><h3>{s.title}</h3><p>{s.desc}</p></li>})}</ol></div></section>
 <section className="v4-works wrap" aria-labelledby="works-title"><div className="v4-section-heading"><h2 id="works-title">다양한 결과물, 하나의 미창</h2><Link href="/works">분야별 사례 보기<ArrowUpRight size={15}/></Link></div>{previewMode?<><p className="v4-preview-note">디자인 방향을 보여주는 예시입니다. 실제 제작 사례는 공개 승인 후 등록합니다.</p><div className="v4-work-grid">{services.map(s=><Link className={'v4-work-card v4-work-'+s.id} href={'/works/'+s.id+'-study'} key={s.id}><div className="v4-work-photo"><MockupPhoto kind={'work-'+s.id} alt={s.example+' — 디자인 예시'}/><span className="v4-work-caption"><strong>{s.name}</strong><span>디자인 예시</span><ArrowUpRight size={16}/></span></div><h3>{s.example}</h3><p>예시 범위: {s.range}</p></Link>)}</div></>:<p className="notice">공개 가능한 제작 사례를 준비하고 있습니다. 서비스 페이지에서 제작 범위를 확인해 주세요.</p>}</section>
 <section className="v4-about"><MockupPhoto kind="about" alt="인쇄물과 색상 자료를 살펴보는 작업 과정 연출 이미지" className="v4-about-photo"/><div className="wrap v4-about-inner"><div><h2>34년의 제작 경험,<br/>새로운 표현으로 이어갑니다.</h2><p>공공기관과 기업을 위한 디자인·인쇄·제본 제작 경험.</p><Link className="v4-outline-link" href="/about">미창 소개<ArrowRight size={17}/></Link></div><nav aria-label="제작 전 안내" className="v4-guide-nav">{[['process','제작 과정'],['prepare','견적 준비자료'],['faq','자주 묻는 질문']].map(([id,label])=><Link key={id} href={'/guide#'+id}>{label}<ArrowRight size={17}/></Link>)}</nav></div><span className="v4-image-note">연출 이미지</span></section>
 <section className="v4-contact"><MockupPhoto kind="contact" alt="햇살이 드는 책상 위 노트와 펜의 연출 이미지" className="v4-contact-photo"/><div className="wrap v4-contact-inner"><div><h2>지금 필요한 프로젝트를 들려주세요.</h2><p>좋은 이야기가 좋은 결과로 이어집니다.</p></div><div className="v4-contact-actions"><Link className="button" href="/contact">제작 견적 문의<ArrowRight size={18}/></Link><a href={company.tel}><Phone size={15}/>{company.phone}</a></div></div></section>
 </div>}
