'use client';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { useState } from 'react';
import { ArrowUpRight, Menu, X, Phone, Mail, ChevronDown } from 'lucide-react';
import { company, services, processSteps, previewMode, type Service } from '@/lib/content';
import HomeV4 from '@/components/home-v4';
import { MockupPhoto } from '@/components/mockup-photo';
export function Header() {
 const path=usePathname(); const [open,setOpen]=useState(false);
 return <header className={path === "/" ? "header header-home" : "header"}><div className="wrap header-row"><Link href="/" className="logo" onClick={()=>setOpen(false)}>디자인미창<span>IDEAS FOR A BETTER TOMORROW</span></Link><button className="mobile-menu" onClick={()=>setOpen(!open)} aria-expanded={open} aria-controls="navigation" aria-label={open?'메뉴 닫기':'메뉴 열기'}>{open?<X/>:<Menu/>}</button><nav id="navigation" aria-label="주 메뉴" className={open?'navigation open':'navigation'}>{[['/about','미창 소개'],['/services','서비스'],['/works','제작 사례'],['/guide','제작 안내'],['/contact','견적 문의']].map(([href,label])=><div className="nav-entry" key={href}><Link className={(path.startsWith(href)?'active ':'')+(href==='/contact'?'nav-contact':'')} aria-current={path===href?'page':undefined} href={href} onClick={()=>setOpen(false)}>{label}{href==='/contact'?<ArrowUpRight size={16}/>:null}</Link>{href==='/services'&&<details className="service-menu"><summary aria-label="서비스 상세 메뉴"><ChevronDown size={15}/></summary><div>{services.map(s=><Link key={s.id} href={'/services/'+s.id} onClick={(e)=>{setOpen(false);e.currentTarget.closest('details')?.removeAttribute('open');}}>{s.name}</Link>)}</div></details>}</div>)}</nav></div></header>;
}
export function CTA({service,label='제작 견적 문의'}:{service?:string;label?:string}) {return <Link className="button" href={'/contact'+(service?'?service='+service:'')}>{label}<ArrowUpRight size={18}/></Link>}
export function SectionTitle({eyebrow,title,text,href,link}:{eyebrow:string;title:string;text?:string;href?:string;link?:string}) {return <div className="section-heading"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2>{text&&<p className="muted">{text}</p>}</div>{href&&<Link className="text-link" href={href}>{link}<ArrowUpRight size={18}/></Link>}</div>}
export function Scene({id,className=''}:{id?:string;className?:string}) {return <div className={'scene reference-scene '+(id?'scene-'+id:'')+' '+className}><MockupPhoto kind={id??'hero'} alt={id?services.find(s=>s.id===id)?.name+' 분야의 디자인 예시':'브랜드 패키지, 영상·웹 화면, 카탈로그와 책자가 있는 작업 공간 디자인 예시'}/></div>}
export function ServiceCards(){return <div className="service-grid">{services.map((s,i)=><Link className="service-card" href={'/services/'+s.id} key={s.id}><Scene id={s.id}/><div className="card-topline"><span className="eyebrow">0{i+1} / {s.en}</span><ArrowUpRight size={20}/></div><h3>{s.name}</h3><p>{s.short}</p></Link>)}</div>}
export function Process(){return <div className="process-grid">{processSteps.map((p,i)=><div key={p.title}><span className="step-number">0{i+1}</span><h3>{p.title}</h3><p>{p.desc}</p></div>)}</div>}
export function ExampleCard({s}:{s:Service}){return <Link className="work-card" href={'/works/'+s.id+'-study'}><Scene id={s.id}/><div className="work-meta"><span>{s.name}</span><span className="example-label">디자인 예시 · 실제 실적 아님</span></div><h3>{s.example}<ArrowUpRight size={21}/></h3><p>예시 범위: {s.range}</p></Link>}
export function Examples({service}:{service?:string}){if(!previewMode)return <p className="notice">공개 가능한 제작 사례를 준비하고 있습니다. 필요한 분야의 서비스와 제작 범위를 먼저 살펴보세요.</p>;return <div className="work-grid">{services.filter(s=>!service||s.id===service).map(s=><ExampleCard key={s.id} s={s}/>)}</div>}
export function ContactBand(){return <section className="contact-band"><div className="wrap"><div><p className="eyebrow">LET’S CREATE TOGETHER</p><h2>지금 필요한 프로젝트를<br/>들려주세요.</h2><p>작은 질문에서, 좋은 제작이 시작됩니다.</p></div><div className="contact-band-actions"><CTA/><a href={company.tel} className="phone-link"><Phone size={19}/>{company.phone}</a></div></div></section>}
export function Footer(){return <footer className="v4-footer"><div className="wrap"><div className="v4-footer-main"><Link href="/" className="logo">디자인미창<span>IDEAS FOR A BETTER TOMORROW</span></Link><div className="v4-footer-contact"><a href={company.tel}><Phone size={18}/>{company.phone}</a><a href={'mailto:'+company.email}><Mail size={18}/>{company.email}</a></div><p className="v4-footer-motto">좋은 디자인이<br/>더 나은 내일을 만듭니다.</p></div><div className="footer-bottom"><span>© {new Date().getFullYear()} 디자인미창 · {company.address} (상세 주소 확인 중)</span>{previewMode&&<span>비공개 디자인 미리보기 · 예시는 실제 실적이 아닙니다.</span>}</div></div></footer>}
export function Home(){return <HomeV4/>}
export function PageIntro({label,title,desc}:{label:string;title:string;desc?:string}){return <section className="page-intro wrap"><p className="breadcrumb"><Link href="/">홈</Link><span>/</span>{label}</p><p className="eyebrow">DESIGN MICHANG / {label}</p><h1>{title}</h1>{desc&&<p className="lead">{desc}</p>}</section>}
export function Faq({items}:{items:string[][]}){return <div className="faq">{items.map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div>}
